
/***************************************************
 * * *                                         * * *
 * * *      * * * DO NOT MODIFY * * *          * * *
 * * *                                         * * *
 * * * Automatically generated by burt-hash.py * * *
****************************************************/
#include "burt-hash.h"
    

static uint32_t hash0(uint32_t x) {
	x -= x << 6;
	x ^= x >> 17;
	x -= x << 9;
	x ^= x << 4;
	x -= x << 3;
	x ^= x << 10;
	x ^= x >> 15;
	return x;
}

static __v4si hash0(__v4si x) {
	x -= x << 6;
	x ^= x >> 17;
	x -= x << 9;
	x ^= x << 4;
	x -= x << 3;
	x ^= x << 10;
	x ^= x >> 15;
	return x;
}

static uint32_t hash1(uint32_t x) {
	x -= x << 6;
	x ^= x >> 17;
	x -= x << 10;
	x ^= x << 5;
	x -= x << 3;
	x ^= x << 9;
	x ^= x >> 16;
	return x;
}

static __v4si hash1(__v4si x) {
	x -= x << 6;
	x ^= x >> 17;
	x -= x << 10;
	x ^= x << 5;
	x -= x << 3;
	x ^= x << 9;
	x ^= x >> 16;
	return x;
}

static uint32_t hash2(uint32_t x) {
	x -= x << 6;
	x ^= x >> 18;
	x += x << 9;
	x ^= x >> 4;
	x -= x << 3;
	x ^= x >> 11;
	x -= x << 14;
	return x;
}

static __v4si hash2(__v4si x) {
	x -= x << 6;
	x ^= x >> 18;
	x += x << 9;
	x ^= x >> 4;
	x -= x << 3;
	x ^= x >> 11;
	x -= x << 14;
	return x;
}

static uint32_t hash3(uint32_t x) {
	x -= x << 6;
	x ^= x >> 18;
	x += x << 11;
	x ^= x << 2;
	x += x << 8;
	x ^= x << 4;
	x ^= x >> 16;
	return x;
}

static __v4si hash3(__v4si x) {
	x -= x << 6;
	x ^= x >> 18;
	x += x << 11;
	x ^= x << 2;
	x += x << 8;
	x ^= x << 4;
	x ^= x >> 16;
	return x;
}

static uint32_t hash4(uint32_t x) {
	x -= x << 6;
	x ^= x >> 18;
	x -= x << 10;
	x ^= x << 5;
	x -= x << 3;
	x ^= x << 9;
	x ^= x >> 16;
	return x;
}

static __v4si hash4(__v4si x) {
	x -= x << 6;
	x ^= x >> 18;
	x -= x << 10;
	x ^= x << 5;
	x -= x << 3;
	x ^= x << 9;
	x ^= x >> 16;
	return x;
}

static uint32_t hash5(uint32_t x) {
	x -= x << 6;
	x ^= x >> 18;
	x ^= x << 14;
	x -= x << 5;
	x ^= x << 7;
	x -= x << 3;
	x ^= x >> 15;
	return x;
}

static __v4si hash5(__v4si x) {
	x -= x << 6;
	x ^= x >> 18;
	x ^= x << 14;
	x -= x << 5;
	x ^= x << 7;
	x -= x << 3;
	x ^= x >> 15;
	return x;
}

static uint32_t hash6(uint32_t x) {
	x -= x << 7;
	x ^= x >> 17;
	x -= x << 9;
	x ^= x << 4;
	x += x << 2;
	x ^= x << 10;
	x ^= x >> 16;
	return x;
}

static __v4si hash6(__v4si x) {
	x -= x << 7;
	x ^= x >> 17;
	x -= x << 9;
	x ^= x << 4;
	x += x << 2;
	x ^= x << 10;
	x ^= x >> 16;
	return x;
}

static uint32_t hash7(uint32_t x) {
	x -= x << 7;
	x ^= x >> 18;
	x += x << 9;
	x ^= x >> 5;
	x += x << 2;
	x ^= x >> 11;
	x += x << 17;
	return x;
}

static __v4si hash7(__v4si x) {
	x -= x << 7;
	x ^= x >> 18;
	x += x << 9;
	x ^= x >> 5;
	x += x << 2;
	x ^= x >> 11;
	x += x << 17;
	return x;
}

static uint32_t hash8(uint32_t x) {
	x -= x << 7;
	x ^= x >> 18;
	x += x << 9;
	x ^= x >> 5;
	x += x << 2;
	x ^= x >> 11;
	x -= x << 17;
	return x;
}

static __v4si hash8(__v4si x) {
	x -= x << 7;
	x ^= x >> 18;
	x += x << 9;
	x ^= x >> 5;
	x += x << 2;
	x ^= x >> 11;
	x -= x << 17;
	return x;
}

static uint32_t hash9(uint32_t x) {
	x -= x << 7;
	x ^= x >> 18;
	x -= x << 5;
	x ^= x >> 3;
	x -= x << 7;
	x ^= x >> 13;
	x -= x << 18;
	return x;
}

static __v4si hash9(__v4si x) {
	x -= x << 7;
	x ^= x >> 18;
	x -= x << 5;
	x ^= x >> 3;
	x -= x << 7;
	x ^= x >> 13;
	x -= x << 18;
	return x;
}

static uint32_t hash10(uint32_t x) {
	x -= x << 7;
	x ^= x >> 19;
	x -= x << 4;
	x ^= x << 3;
	x -= x << 6;
	x -= x << 12;
	x ^= x >> 16;
	return x;
}

static __v4si hash10(__v4si x) {
	x -= x << 7;
	x ^= x >> 19;
	x -= x << 4;
	x ^= x << 3;
	x -= x << 6;
	x -= x << 12;
	x ^= x >> 16;
	return x;
}

static uint32_t hash11(uint32_t x) {
	x -= x << 7;
	x ^= x >> 19;
	x -= x << 5;
	x ^= x << 6;
	x -= x << 3;
	x ^= x >> 14;
	x += x << 11;
	return x;
}

static __v4si hash11(__v4si x) {
	x -= x << 7;
	x ^= x >> 19;
	x -= x << 5;
	x ^= x << 6;
	x -= x << 3;
	x ^= x >> 14;
	x += x << 11;
	return x;
}

static uint32_t hash12(uint32_t x) {
	x -= x << 7;
	x ^= x >> 19;
	x -= x << 9;
	x ^= x << 10;
	x -= x << 4;
	x ^= x << 3;
	x ^= x >> 15;
	return x;
}

static __v4si hash12(__v4si x) {
	x -= x << 7;
	x ^= x >> 19;
	x -= x << 9;
	x ^= x << 10;
	x -= x << 4;
	x ^= x << 3;
	x ^= x >> 15;
	return x;
}

static uint32_t hash13(uint32_t x) {
	x -= x << 7;
	x ^= x >> 20;
	x += x << 4;
	x ^= x >> 8;
	x += x << 6;
	x ^= x >> 11;
	x += x << 16;
	return x;
}

static __v4si hash13(__v4si x) {
	x -= x << 7;
	x ^= x >> 20;
	x += x << 4;
	x ^= x >> 8;
	x += x << 6;
	x ^= x >> 11;
	x += x << 16;
	return x;
}

static uint32_t hash14(uint32_t x) {
	x -= x << 7;
	x ^= x >> 20;
	x += x << 10;
	x ^= x >> 5;
	x += x << 8;
	x ^= x << 11;
	x ^= x >> 17;
	return x;
}

static __v4si hash14(__v4si x) {
	x -= x << 7;
	x ^= x >> 20;
	x += x << 10;
	x ^= x >> 5;
	x += x << 8;
	x ^= x << 11;
	x ^= x >> 17;
	return x;
}

static uint32_t hash15(uint32_t x) {
	x -= x << 8;
	x ^= x >> 17;
	x += x << 12;
	x ^= x >> 3;
	x -= x << 7;
	x ^= x << 5;
	x ^= x >> 16;
	return x;
}

static __v4si hash15(__v4si x) {
	x -= x << 8;
	x ^= x >> 17;
	x += x << 12;
	x ^= x >> 3;
	x -= x << 7;
	x ^= x << 5;
	x ^= x >> 16;
	return x;
}

static uint32_t hash16(uint32_t x) {
	x -= x << 8;
	x ^= x >> 17;
	x += x << 13;
	x ^= x >> 3;
	x += x << 6;
	x ^= x << 5;
	x ^= x >> 17;
	return x;
}

static __v4si hash16(__v4si x) {
	x -= x << 8;
	x ^= x >> 17;
	x += x << 13;
	x ^= x >> 3;
	x += x << 6;
	x ^= x << 5;
	x ^= x >> 17;
	return x;
}

static uint32_t hash17(uint32_t x) {
	x -= x << 8;
	x ^= x >> 17;
	x -= x << 6;
	x ^= x >> 5;
	x += x << 2;
	x ^= x >> 10;
	x += x << 16;
	return x;
}

static __v4si hash17(__v4si x) {
	x -= x << 8;
	x ^= x >> 17;
	x -= x << 6;
	x ^= x >> 5;
	x += x << 2;
	x ^= x >> 10;
	x += x << 16;
	return x;
}

static uint32_t hash18(uint32_t x) {
	x -= x << 8;
	x ^= x >> 17;
	x -= x << 6;
	x ^= x >> 5;
	x += x << 2;
	x ^= x >> 10;
	x -= x << 16;
	return x;
}

static __v4si hash18(__v4si x) {
	x -= x << 8;
	x ^= x >> 17;
	x -= x << 6;
	x ^= x >> 5;
	x += x << 2;
	x ^= x >> 10;
	x -= x << 16;
	return x;
}

static uint32_t hash19(uint32_t x) {
	x -= x << 8;
	x ^= x >> 18;
	x += x << 3;
	x ^= x >> 6;
	x += x << 8;
	x ^= x >> 13;
	x += x << 15;
	return x;
}

static __v4si hash19(__v4si x) {
	x -= x << 8;
	x ^= x >> 18;
	x += x << 3;
	x ^= x >> 6;
	x += x << 8;
	x ^= x >> 13;
	x += x << 15;
	return x;
}

static uint32_t hash20(uint32_t x) {
	x -= x << 8;
	x ^= x >> 18;
	x -= x << 5;
	x ^= x >> 3;
	x += x << 7;
	x ^= x << 13;
	x ^= x >> 17;
	return x;
}

static __v4si hash20(__v4si x) {
	x -= x << 8;
	x ^= x >> 18;
	x -= x << 5;
	x ^= x >> 3;
	x += x << 7;
	x ^= x << 13;
	x ^= x >> 17;
	return x;
}

static uint32_t hash21(uint32_t x) {
	x -= x << 9;
	x ^= x >> 17;
	x += x << 11;
	x ^= x >> 4;
	x += x << 7;
	x ^= x << 5;
	x ^= x >> 15;
	return x;
}

static __v4si hash21(__v4si x) {
	x -= x << 9;
	x ^= x >> 17;
	x += x << 11;
	x ^= x >> 4;
	x += x << 7;
	x ^= x << 5;
	x ^= x >> 15;
	return x;
}

static uint32_t hash22(uint32_t x) {
	x -= x << 10;
	x ^= x >> 18;
	x -= x << 12;
	x ^= x >> 3;
	x -= x << 6;
	x ^= x << 8;
	x ^= x >> 17;
	return x;
}

static __v4si hash22(__v4si x) {
	x -= x << 10;
	x ^= x >> 18;
	x -= x << 12;
	x ^= x >> 3;
	x -= x << 6;
	x ^= x << 8;
	x ^= x >> 17;
	return x;
}

static uint32_t hash23(uint32_t x) {
	x -= x << 11;
	x ^= x >> 19;
	x += x << 7;
	x ^= x >> 5;
	x += x << 3;
	x ^= x >> 13;
	x -= x << 16;
	return x;
}

static __v4si hash23(__v4si x) {
	x -= x << 11;
	x ^= x >> 19;
	x += x << 7;
	x ^= x >> 5;
	x += x << 3;
	x ^= x >> 13;
	x -= x << 16;
	return x;
}

static uint32_t hash24(uint32_t x) {
	x -= x << 12;
	x ^= x >> 18;
	x -= x << 4;
	x ^= x >> 9;
	x -= x << 6;
	x ^= x >> 12;
	x += x << 16;
	return x;
}

static __v4si hash24(__v4si x) {
	x -= x << 12;
	x ^= x >> 18;
	x -= x << 4;
	x ^= x >> 9;
	x -= x << 6;
	x ^= x >> 12;
	x += x << 16;
	return x;
}

static uint32_t hash25(uint32_t x) {
	x -= x << 12;
	x ^= x >> 18;
	x -= x << 5;
	x ^= x >> 6;
	x -= x << 3;
	x ^= x >> 11;
	x += x << 16;
	return x;
}

static __v4si hash25(__v4si x) {
	x -= x << 12;
	x ^= x >> 18;
	x -= x << 5;
	x ^= x >> 6;
	x -= x << 3;
	x ^= x >> 11;
	x += x << 16;
	return x;
}

static uint32_t hash26(uint32_t x) {
	x -= x << 12;
	x ^= x >> 18;
	x -= x << 9;
	x ^= x >> 5;
	x += x << 2;
	x ^= x >> 13;
	x += x << 16;
	return x;
}

static __v4si hash26(__v4si x) {
	x -= x << 12;
	x ^= x >> 18;
	x -= x << 9;
	x ^= x >> 5;
	x += x << 2;
	x ^= x >> 13;
	x += x << 16;
	return x;
}

static uint32_t hash27(uint32_t x) {
	x -= x << 13;
	x ^= x >> 17;
	x -= x << 5;
	x ^= x >> 6;
	x += x << 3;
	x ^= x >> 12;
	x -= x << 15;
	return x;
}

static __v4si hash27(__v4si x) {
	x -= x << 13;
	x ^= x >> 17;
	x -= x << 5;
	x ^= x >> 6;
	x += x << 3;
	x ^= x >> 12;
	x -= x << 15;
	return x;
}

static uint32_t hash28(uint32_t x) {
	x -= x << 13;
	x ^= x >> 17;
	x -= x << 5;
	x ^= x >> 9;
	x -= x << 3;
	x ^= x >> 8;
	x += x << 17;
	return x;
}

static __v4si hash28(__v4si x) {
	x -= x << 13;
	x ^= x >> 17;
	x -= x << 5;
	x ^= x >> 9;
	x -= x << 3;
	x ^= x >> 8;
	x += x << 17;
	return x;
}

static uint32_t hash29(uint32_t x) {
	x -= x << 13;
	x ^= x >> 17;
	x -= x << 5;
	x ^= x >> 9;
	x -= x << 3;
	x ^= x >> 8;
	x -= x << 15;
	return x;
}

static __v4si hash29(__v4si x) {
	x -= x << 13;
	x ^= x >> 17;
	x -= x << 5;
	x ^= x >> 9;
	x -= x << 3;
	x ^= x >> 8;
	x -= x << 15;
	return x;
}

static uint32_t hash30(uint32_t x) {
	x -= x << 13;
	x ^= x >> 17;
	x -= x << 7;
	x ^= x >> 3;
	x -= x << 5;
	x ^= x << 12;
	x ^= x >> 15;
	return x;
}

static __v4si hash30(__v4si x) {
	x -= x << 13;
	x ^= x >> 17;
	x -= x << 7;
	x ^= x >> 3;
	x -= x << 5;
	x ^= x << 12;
	x ^= x >> 15;
	return x;
}

static uint32_t hash31(uint32_t x) {
	x -= x << 13;
	x ^= x >> 17;
	x -= x << 10;
	x ^= x >> 5;
	x += x << 2;
	x ^= x >> 13;
	x -= x << 14;
	return x;
}

static __v4si hash31(__v4si x) {
	x -= x << 13;
	x ^= x >> 17;
	x -= x << 10;
	x ^= x >> 5;
	x += x << 2;
	x ^= x >> 13;
	x -= x << 14;
	return x;
}

static uint32_t hash32(uint32_t x) {
	x -= x << 13;
	x ^= x >> 17;
	x -= x << 10;
	x ^= x >> 5;
	x += x << 2;
	x ^= x >> 13;
	x -= x << 18;
	return x;
}

static __v4si hash32(__v4si x) {
	x -= x << 13;
	x ^= x >> 17;
	x -= x << 10;
	x ^= x >> 5;
	x += x << 2;
	x ^= x >> 13;
	x -= x << 18;
	return x;
}

static uint32_t hash33(uint32_t x) {
	x -= x << 14;
	x ^= x >> 17;
	x -= x << 10;
	x ^= x >> 5;
	x -= x << 3;
	x ^= x >> 14;
	x -= x << 15;
	return x;
}

static __v4si hash33(__v4si x) {
	x -= x << 14;
	x ^= x >> 17;
	x -= x << 10;
	x ^= x >> 5;
	x -= x << 3;
	x ^= x >> 14;
	x -= x << 15;
	return x;
}

static uint32_t hash34(uint32_t x) {
	x -= x << 14;
	x ^= x >> 17;
	x -= x << 10;
	x ^= x >> 5;
	x -= x << 3;
	x ^= x >> 14;
	x -= x << 18;
	return x;
}

static __v4si hash34(__v4si x) {
	x -= x << 14;
	x ^= x >> 17;
	x -= x << 10;
	x ^= x >> 5;
	x -= x << 3;
	x ^= x >> 14;
	x -= x << 18;
	return x;
}

burt_hash::function * burt_hash::select_hash(uint32_t selector) {
	switch(selector % 35) {
	default:
	case 0: return &hash0;
	case 1: return &hash1;
	case 2: return &hash2;
	case 3: return &hash3;
	case 4: return &hash4;
	case 5: return &hash5;
	case 6: return &hash6;
	case 7: return &hash7;
	case 8: return &hash8;
	case 9: return &hash9;
	case 10: return &hash10;
	case 11: return &hash11;
	case 12: return &hash12;
	case 13: return &hash13;
	case 14: return &hash14;
	case 15: return &hash15;
	case 16: return &hash16;
	case 17: return &hash17;
	case 18: return &hash18;
	case 19: return &hash19;
	case 20: return &hash20;
	case 21: return &hash21;
	case 22: return &hash22;
	case 23: return &hash23;
	case 24: return &hash24;
	case 25: return &hash25;
	case 26: return &hash26;
	case 27: return &hash27;
	case 28: return &hash28;
	case 29: return &hash29;
	case 30: return &hash30;
	case 31: return &hash31;
	case 32: return &hash32;
	case 33: return &hash33;
	case 34: return &hash34;
	}
}

burt_hash4::function * burt_hash4::select_hash(uint32_t selector) {
	switch(selector % 35) {
	default:
	case 0: return &hash0;
	case 1: return &hash1;
	case 2: return &hash2;
	case 3: return &hash3;
	case 4: return &hash4;
	case 5: return &hash5;
	case 6: return &hash6;
	case 7: return &hash7;
	case 8: return &hash8;
	case 9: return &hash9;
	case 10: return &hash10;
	case 11: return &hash11;
	case 12: return &hash12;
	case 13: return &hash13;
	case 14: return &hash14;
	case 15: return &hash15;
	case 16: return &hash16;
	case 17: return &hash17;
	case 18: return &hash18;
	case 19: return &hash19;
	case 20: return &hash20;
	case 21: return &hash21;
	case 22: return &hash22;
	case 23: return &hash23;
	case 24: return &hash24;
	case 25: return &hash25;
	case 26: return &hash26;
	case 27: return &hash27;
	case 28: return &hash28;
	case 29: return &hash29;
	case 30: return &hash30;
	case 31: return &hash31;
	case 32: return &hash32;
	case 33: return &hash33;
	case 34: return &hash34;
	}
}

